### ISSUE TITLE
Reach 50% code coverage with PHPUnit

### ISSUE THREAD

**Issue by sourcerer-mike** [sourcerer-mike/phpsemver#20]
50% code coverage in Methods.

**Comment by sourcerer-mike** [comment]
Yay!

```
 Summary:                 
  Classes: 25.00% (1/4)   
  Methods: 33.33% (6/18)  
  Lines:   17.65% (24/136)

```

**Comment by sourcerer-mike** [comment]
```
 Summary:                 
  Classes: 50.00% (2/4)   
  Methods: 78.95% (15/19) 
  Lines:   65.19% (88/135)
```
